masastack/MASA.Stack.Components

- src/Masa.Stack.Components/Layouts/Layout.razor.cs
- src/Masa.Stack.Components/Masa.Stack.Components.csproj
- src/Masa.Stack.Components/Users/UserAutoComplete.razor
- src/Masa.Stack.Components/Users/UserAutoComplete.razor.cs
- src/Masa.Stack.Components/Users/ViewModel/UserSelect.cs
- src/Masa.Stack.Components/Users/ViewModel/UserSelectModel.cs
- src/Masa.Stack.Components/_Imports.cs
- tests/MasaWebApp/MasaWebApp.csproj
- tests/MasaWebApp/Pages/UseUserAutoComplete.razor
- tests/MasaWebApp/Program.cs
- tests/MasaWebApp/wwwroot/css/masa-blazor-pro.css
- tests/MasaWebApp/wwwroot/i18n/zh-CN.json
Add UserAutoComplete [#6](https://github.com/masastack/MASA.Stack.Components/pull/6)
> Feature：Add UserAutoComplete

- src/Masa.Stack.Components/GlobalNavigations/ExpansionApp.razor
- src/Masa.Stack.Components/GlobalNavigations/ExpansionApp.razor.cs
- src/Masa.Stack.Components/GlobalNavigations/ExpansionAppItem.razor
- src/Masa.Stack.Components/GlobalNavigations/GlobalNavigation.razor
- src/Masa.Stack.Components/GlobalNavigations/GlobalNavigation.razor.cs
- src/Masa.Stack.Components/IntegrationComponents/Defaults/DefaultTextField.cs
- src/Masa.Stack.Components/Layouts/Components/Favorites.razor.cs
- src/Masa.Stack.Components/Layouts/Components/Languages.razor
- src/Masa.Stack.Components/Masa.Stack.Components.csproj
- src/Masa.Stack.Components/Models/Nav.cs
- src/Masa.Stack.Components/Models/NavAction.cs
- src/Masa.Stack.Components/PureComponents/AutoLoadingButton.cs
- src/Masa.Stack.Components/wwwroot/css/app.css
- src/Masa.Stack.Components/wwwroot/css/standard.css
> feat: Support action level

- src/Masa.Stack.Components/GlobalNavigations/ExpansionApp.razor
- src/Masa.Stack.Components/GlobalNavigations/ExpansionApp.razor.cs
- src/Masa.Stack.Components/GlobalNavigations/ExpansionAppItem.razor
- src/Masa.Stack.Components/GlobalNavigations/ExpansionCategory.razor
- src/Masa.Stack.Components/GlobalNavigations/ExpansionCategory.razor.cs
- src/Masa.Stack.Components/GlobalNavigations/ExpansionWrapper.razor
- src/Masa.Stack.Components/GlobalNavigations/ExpansionWrapper.razor.cs
- src/Masa.Stack.Components/GlobalNavigations/GlobalNavigation.razor.cs
- src/Masa.Stack.Components/IntegrationComponents/Tab/ElevationTab.razor
- src/Masa.Stack.Components/Layouts/Layout.razor.cs
- src/Masa.Stack.Components/Masa.Stack.Components.csproj
- src/Masa.Stack.Components/Models/Category.cs
- tests/MasaWebApp/Pages/Index.razor
> 🆕 feat(ExpansionCategory): support preview mode

- src/Masa.Stack.Components/GlobalNavigations/ExpansionApp.razor
- src/Masa.Stack.Components/GlobalNavigations/ExpansionApp.razor.cs
- src/Masa.Stack.Components/GlobalNavigations/ExpansionAppItem.razor
- src/Masa.Stack.Components/GlobalNavigations/ExpansionWrapper.razor.cs
- src/Masa.Stack.Components/Models/CategoryAppNav.cs
> 🐛 fix(ExpansionCategory): Missing action value

- src/Masa.Stack.Components/GlobalNavigations/GlobalNavigation.razor.cs
- src/Masa.Stack.Components/Models/CategoryAppNavModel.cs
- src/Masa.Stack.Components/Models/Nav.cs
- src/Masa.Stack.Components/PureComponents/LabeledRadios/LabeledRadioGroup.razor
fix favorite menu not show question
> feat(nav):modify favorite menu

- src/Masa.Stack.Components/Layouts/Components/Notification.razor
- src/Masa.Stack.Components/Layouts/Components/Notification.razor.cs
- src/Masa.Stack.Components/Masa.Stack.Components.csproj
- src/Masa.Stack.Components/NotificationCenters/NotificationRight.razor
- tests/MasaWebApp/MasaWebApp.csproj
- tests/MasaWebApp/Program.cs
SignalR add token verification
> refactor：SignalR add token verification

- src/Masa.Stack.Components/Masa.Stack.Components.csproj
- src/Masa.Stack.Components/NotificationCenters/NotificationRight.razor
Pagination add full-width class
> style(notificationCenters)：pagination add full-width class

- src/Masa.Stack.Components/IntegrationComponents/Users/UserAutoComplete.razor
- src/Masa.Stack.Components/IntegrationComponents/Users/UserAutoComplete.razor.cs
Add custom property on UserAutoComplete
> feat(UserAutoComplete): Add custom property

- src/Masa.Stack.Components/IntegrationComponents/Users/UserAutoComplete.razor
- src/Masa.Stack.Components/IntegrationComponents/Users/UserAutoComplete.razor.cs
> feat(UserAutoComplete): add placeholder property

- src/Masa.Stack.Components/IntegrationComponents/Users/UserAutoComplete.razor
- src/Masa.Stack.Components/IntegrationComponents/Users/UserAutoComplete.razor.cs
add PersistentPlaceholder property
> feat(UserAutoComplete): add PersistentPlaceholder property

- src/Masa.Stack.Components/JsInterop/JsInitVariables.cs
- src/Masa.Stack.Components/Layouts/Layout.razor
- src/Masa.Stack.Components/Layouts/Layout.razor.cs
- src/Masa.Stack.Components/wwwroot/Masa.Stack.Components.lib.module.js
- tests/MasaWebApp/Pages/Index.razor
- tests/MasaWebApp/_Imports.razor
通过JavaScript initializers的afterStarted方法里调用.net静态方法，设置静态变量TimezoneOffset。之前的级联会很麻烦。
usage:
``` c#
using static Masa.Stack.Components.JsInitVariables;
var localDateTime = DateTime.UtcNow.Add(TimezoneOffset);
```
> ⚡ refactor: make TimezoneOffset static

- src/Masa.Stack.Components/Layouts/Components/Notification.razor
- src/Masa.Stack.Components/NotificationCenters/NotificationDetail.razor
- src/Masa.Stack.Components/NotificationCenters/NotificationRight.razor
Time is displayed in local time zone
> refactor：Time is displayed in local time zone

- src/Masa.Stack.Components/Layouts/SLayout.razor
- src/Masa.Stack.Components/Layouts/SLayout.razor.cs
> feat(SLayout): add breadcrumbs in SLayout

- src/Masa.Stack.Components/Locales/zh-CN.json
- src/Masa.Stack.Components/Masa.Stack.Components.csproj
- src/Masa.Stack.Components/Pages/UserCenters/UploadAvatar.cs
- src/Masa.Stack.Components/Shared/IntegrationComponents/SUrlTextField.razor
- src/Masa.Stack.Components/Shared/IntegrationComponents/Upload/SUpload.razor.cs
> Feature(uploadAvatar):UploadAvatar Component not support gif

- src/Masa.Stack.Components/Models/IconConstants.cs
- src/Masa.Stack.Components/Shared/IntegrationComponents/SAutoComplete.cs
- src/Masa.Stack.Components/Shared/IntegrationComponents/SSelect.cs
- src/Masa.Stack.Components/Shared/IntegrationComponents/STextField.cs
> Feature: tsc

- src/Masa.Stack.Components/Masa.Stack.Components.csproj
- src/Masa.Stack.Components/Shared/IntegrationComponents/Users/SUserAutoComplete.razor
- src/Masa.Stack.Components/Shared/IntegrationComponents/Users/SUserAutoComplete.razor.cs
- tests/MasaWebApp/MasaWebApp.csproj
> Feature user auto complete clearble

- src/Masa.Stack.Components/Shared/IntegrationComponents/ElevationTab/SElevationTab.razor
- tests/MasaWebApp/Pages/Tab.razor
> Feat SElevationTab add active class

- src/Masa.Stack.Components/Shared/IntegrationComponents/SAutoComplete.cs
- src/Masa.Stack.Components/Shared/IntegrationComponents/SSelect.cs
- src/Masa.Stack.Components/Shared/IntegrationComponents/STextField.cs
> Fix auto label

- src/Masa.Stack.Components/Shared/GlobalNavigations/ExpansionAppItem.razor
- src/Masa.Stack.Components/Shared/Layouts/SLayout.razor.cs
> Fix(expansionAppItem): expansion app item

- src/Masa.Stack.Components/Masa.Stack.Components.csproj
> Feature:update nuget packge

- src/Masa.Stack.Components/MasaComponentBase.cs
- src/Masa.Stack.Components/Shared/GlobalNavigations/ExpansionApp.razor
- src/Masa.Stack.Components/Shared/GlobalNavigations/ExpansionAppItem.razor
- src/Masa.Stack.Components/Shared/IntegrationComponents/SSheetDialog.razor
> fix(expanssionApp、ssheetDialog) :fix expanssionApp、ssheetDialog

- src/Masa.Stack.Components/Extensions/ServiceCollectionExtensions.cs
> Fix autocomplete build

- src/Masa.Stack.Components/Masa.Stack.Components.csproj
- src/Masa.Stack.Components/Shared/Layouts/Components/Breadcrumbs.razor
- src/Masa.Stack.Components/Shared/Layouts/Components/Breadcrumbs.razor.cs
> Feature(packge):update nuget packge

- src/Masa.Stack.Components/Extensions/ElasticsearchAutoCompleteExtensions.cs
- src/Masa.Stack.Components/Extensions/OssExtensions.cs
- src/Masa.Stack.Components/Extensions/ServiceCollectionExtensions.cs
- src/Masa.Stack.Components/Masa.Stack.Components.csproj
- src/Masa.Stack.Components/Pages/UserCenters/Modals/VerifyEmailModal.razor.cs
- src/Masa.Stack.Components/Pages/UserCenters/Modals/VerifyPhoneNumberModal.razor.cs
- src/Masa.Stack.Components/Pages/UserCenters/UploadAvatar.cs
- src/Masa.Stack.Components/_Imports.cs
- tests/MasaWebApp/MasaWebApp.csproj
> Feature(nuget packge): update nuget packge

- src/Masa.Stack.Components/JsInterop/JsInitVariables.cs
- src/Masa.Stack.Components/_Imports.cs
- tests/MasaWebApp/Pages/Index.razor
> Feature(JsInitVariables ):JsInitVariables support localStorage

- src/Masa.Stack.Components/Locales/zh-CN.json
- src/Masa.Stack.Components/Models/CategoryAppNav.cs
- src/Masa.Stack.Components/Shared/GlobalNavigations/ExpansionApp.razor
- src/Masa.Stack.Components/Shared/GlobalNavigations/ExpansionApp.razor.cs
- src/Masa.Stack.Components/Shared/GlobalNavigations/ExpansionAppItem.razor
- src/Masa.Stack.Components/Shared/GlobalNavigations/ExpansionAppItem.razor.cs
> Feature(GlobalNavigation): rector GlobalNavigation

- src/Masa.Stack.Components/Shared/IntegrationComponents/SSelect.cs
- src/Masa.Stack.Components/Shared/Layouts/SLayout.razor.cs
- src/Masa.Stack.Components/wwwroot/css/app.css
- tests/MasaWebApp/Pages/Select.razor
Add Vertical line to ```SSelect``` Component.
> feat(SSelect):add vertical line function

- src/Masa.Stack.Components/JsInterop/JsInitVariables.cs
- src/Masa.Stack.Components/Masa.Stack.Components.csproj
- tests/MasaWebApp/MasaWebApp.csproj
> Feature:jsInitVariables use cookie storage

- src/Masa.Stack.Components/Shared/IntegrationComponents/SSheetDialog.razor
> fix(SSheetDialog): onclose stopPropagation

- src/Masa.Stack.Components/JsInterop/JsInitVariables.cs
- tests/MasaWebApp/Pages/Index.razor
> Feature:JsInitVariables TimezoneOffsetChanged

- src/Masa.Stack.Components/Shared/Layouts/Components/Navigation.razor
> fix(Navigation):After entering the page, the left menu is not selected.resolve (#352)

- src/Masa.Stack.Components/Shared/IntegrationComponents/STextField.cs
> feat:update stextfield css

- src/Masa.Stack.Components/Shared/GlobalNavigations/ExpansionApp.razor
- src/Masa.Stack.Components/Shared/GlobalNavigations/ExpansionApp.razor.cs
- src/Masa.Stack.Components/Shared/GlobalNavigations/ExpansionWrapper.razor
- src/Masa.Stack.Components/Shared/GlobalNavigations/ExpansionWrapper.razor.cs
> Fix(global navigations): global navigations show error in preview

- src/Masa.Stack.Components/Shared/GlobalNavigations/GlobalNavigation.razor
- src/Masa.Stack.Components/Shared/GlobalNavigations/GlobalNavigation.razor.cs
repair global navigation invalid cancel collection
> fix:repair global navigation invalid cancel collection

- src/Masa.Stack.Components/Locales/en-US.json
- src/Masa.Stack.Components/Locales/zh-CN.json
> fix:The title of the in-site message list needs to be changed because it conflicts with the MC name.

- src/Masa.Stack.Components/Shared/IntegrationComponents/Users/SUserAutoComplete.razor
- src/Masa.Stack.Components/wwwroot/css/app.css
- tests/MasaWebApp/Pages/DefaultButtonExample.razor
> feat:update SUserAutoComplete css

- src/Masa.Stack.Components/Shared/IntegrationComponents/SSelect.cs
- src/Masa.Stack.Components/wwwroot/css/app.css
_1.SSlect style margin spacing is modified according to the design
2.SSelect Add class if class is not contains_
> SSelect Add class if class is not contains

- src/Masa.Stack.Components/Masa.Stack.Components.csproj
chore: update Masa.Blazor to preview
> chore: update Masa.Blazor to preview 9

- src/Masa.Stack.Components/Shared/IntegrationComponents/Users/SUserAutoComplete.razor
- tests/MasaWebApp/Pages/UserAutoCompleteExample.razor
resolved https://github.com/masastack/MASA.Auth/issues/829
> fix(SUserAutoComplete):'Small' property equals true. The content height is too narrow

- src/Masa.Stack.Components/Shared/IntegrationComponents/Users/SUserAutoComplete.razor.cs
> feat:Solve the problem that UserAutoComplete cannot query the result

- src/Masa.Stack.Components/Shared/IntegrationComponents/SCaptchaSendTextField.razor
> Fix: Tips add InvokeAsync

- src/Masa.Stack.Components/Shared/PureComponents/LabeledRadios/SLabeledRadioGroup.razor
```
<LabeledRadioGroup @ref="Ref">
@code {
private async Task OnLanuageChanged() {
await Ref.CallSlider();
}
}
```
> 🆕 feat(LabeledRadioGroup): expose the CallSlider method

- src/Masa.Stack.Components/Pages/UserCenters/UserInfo.razor
- src/Masa.Stack.Components/Pages/UserCenters/UserInfo.razor.cs
_Fix: user-center i18n language toggle gender styles_
> Fix: user-center i18n language toggle gender styles

- src/Masa.Stack.Components/Shared/Layouts/SLayout.razor
- src/Masa.Stack.Components/wwwroot/css/app.css
> fix:Moving the mouse over the page will penetrate the top navigation bar

- src/Masa.Stack.Components/Shared/IntegrationComponents/SNameTextField.cs
- src/Masa.Stack.Components/wwwroot/css/app.css
Fix this [Issue-841](https://github.com/masastack/MASA.Auth/issues/841)
Move PlaceholderTextField component which is in Masa.Auth to SNameTextField component
> feat: add SNameTextField components

- src/Masa.Stack.Components/Pages/NotificationCenters/NotificationLeft.razor
- src/Masa.Stack.Components/Pages/NotificationCenters/NotificationRight.razor
- src/Masa.Stack.Components/Shared/IntegrationComponents/SPaginationSelect.razor
- src/Masa.Stack.Components/wwwroot/css/app.css
Amend some styles in Notifcation and Login 
There is [Issue-845](https://github.com/masastack/MASA.Auth/issues/845)
> Fix: Amend style for Notification

- src/Masa.Stack.Components/Shared/IntegrationComponents/SSheetDialog.razor
> feat:add SheetValueChangedAsync to ssheetdialog

- src/Masa.Stack.Components/Locales/zh-CN.json
_i18n: Modify the value of the key Add_
> i18n: Modify the value of the key Add

- src/Masa.Stack.Components/Pages/UserCenters/UserInfo.razor.cs
- src/Masa.Stack.Components/Shared/PureComponents/LabeledRadios/SLabeledRadioGroup.razor
- src/Masa.Stack.Components/_Imports.razor
_Fix: user-center i18n language toggle gender styles misaligned_
> Fix: user-center i18n language toggle gender styles misaligned

- src/Masa.Stack.Components/Locales/zh-CN.json
- src/Masa.Stack.Components/Shared/GlobalNavigations/ExpansionApp.razor
- src/Masa.Stack.Components/Shared/GlobalNavigations/ExpansionApp.razor.cs
- src/Masa.Stack.Components/Shared/GlobalNavigations/ExpansionAppItem.razor
- src/Masa.Stack.Components/Shared/GlobalNavigations/ExpansionAppItem.razor.cs
Fix [Issue-588](https://github.com/masastack/MASA.Auth/issues/588)
> Change select rule for permission and favorite

- src/Masa.Stack.Components/Models/App.cs
- src/Masa.Stack.Components/Models/Category.cs
- src/Masa.Stack.Components/Models/Nav.cs
- src/Masa.Stack.Components/Shared/GlobalNavigations/ExpansionApp.razor
- src/Masa.Stack.Components/Shared/GlobalNavigations/ExpansionWrapper.razor
english and chinese language search result:
> fix:Global navigation, search English only appear search results. resolved #446

- src/Masa.Stack.Components/Pages/UserCenters/Models/UpdateUserPhoneNumberValidator.cs
- src/Masa.Stack.Components/Pages/UserCenters/Models/VerifyPhoneNumberValidator.cs
Fix [Issue-445](https://github.com/masastack/MASA.Stack.Components/issues/445)
> Fix: cancel warning for message code length in validator

- src/Masa.Stack.Components/Shared/IntegrationComponents/SDataTable.cs
- src/Masa.Stack.Components/wwwroot/css/app.css
> refactor: SDataTable

- src/Masa.Stack.Components/Locales/zh-CN.json
- src/Masa.Stack.Components/Shared/IntegrationComponents/SAutoCompleteSelection.razor
- src/Masa.Stack.Components/wwwroot/css/app.css
> feat:add SAutoCompleteSelection.razor

- src/Masa.Stack.Components/wwwroot/Masa.Stack.Components.lib.module.js
This is an out-of-date document that is no longer needed
> fix: remove unused file

- src/Masa.Stack.Components/wwwroot/css/app.css
Fix block style for td in SDataTable
> Fix: remove block style for td

- src/Masa.Stack.Components/wwwroot/css/app.css
> fix:Operation log, please select the time drop-down box style to adjust

- src/Masa.Stack.Components/Shared/IntegrationComponents/SSearch.razor
_SSearch add the OnClearClick event_
> SSearch add the OnClearClick event

- src/Masa.Stack.Components/Locales/zh-CN.json
- src/Masa.Stack.Components/Shared/IntegrationComponents/SIcon.razor
- src/Masa.Stack.Components/Shared/IntegrationComponents/SIcon.razor.cs
- src/Masa.Stack.Components/Shared/Layouts/SLayout.razor.cs
- tests/MasaWebApp/Pages/Icons.razor
> feat:add sicon i18N

- src/Masa.Stack.Components/Shared/IntegrationComponents/SSearch.razor
> fix:search staff to click Enter twice to appear search results

- src/Masa.Stack.Components/Shared/IntegrationComponents/SAutoCompleteSelection.razor
> fix:update SAutoCompleteSelection.razor

- src/Masa.Stack.Components/Shared/IntegrationComponents/SAutoCompleteSelection.razor
> Fix issues s auto complete selection

- src/Masa.Stack.Components/Shared/Layouts/Components/Navigation.razor
> fix:Mini menu, containing secondary menu can not be expanded

- src/Masa.Stack.Components/Pages/NotificationCenters/NotificationDetail.razor.cs
- src/Masa.Stack.Components/Shared/IntegrationComponents/SIcon.razor.cs
> fix:Confirm the same popover style for all projects twice

- src/Masa.Stack.Components/Locales/en-US.json
- src/Masa.Stack.Components/Locales/zh-CN.json
- src/Masa.Stack.Components/Pages/NotificationCenters/NotificationDetail.razor
- src/Masa.Stack.Components/Pages/NotificationCenters/NotificationRight.razor
- src/Masa.Stack.Components/Pages/UserCenters/StaffInfo.razor
- src/Masa.Stack.Components/Pages/UserCenters/UserInfo.razor
- src/Masa.Stack.Components/Shared/GlobalNavigations/ExpansionAppItem.razor
- src/Masa.Stack.Components/Shared/GlobalNavigations/GlobalNavigation.razor
- src/Masa.Stack.Components/Shared/IntegrationComponents/SDeleteButton.razor
- src/Masa.Stack.Components/Shared/IntegrationComponents/SIcon.razor.cs
- src/Masa.Stack.Components/Shared/IntegrationComponents/SSearchableExtend.razor
- src/Masa.Stack.Components/Shared/IntegrationComponents/SSimpleDialog.razor
- src/Masa.Stack.Components/Shared/IntegrationComponents/SSimpleModal.cs
- src/Masa.Stack.Components/Shared/Layouts/Components/Favorites.razor
> fix:Only icon button, mouse hover, should have tooltips

- src/Masa.Stack.Components/Shared/IntegrationComponents/DateTime/SDateRangePicker.razor
- src/Masa.Stack.Components/Shared/IntegrationComponents/DateTime/SDateRangePicker.razor.cs
- src/Masa.Stack.Components/Shared/IntegrationComponents/DateTime/SDateTimeRangePicker.razor
- tests/MasaWebApp/Pages/DateRangePickerExample.razor
style: date range and datetime ranger picker
> style: date range and datetime ranger picker

- src/Masa.Stack.Components/Shared/Layouts/Components/Navigation.razor
> fix:MMenu Disabled will not be re rendered after being set back to false

- src/Masa.Stack.Components/Shared/Layouts/Components/Navigation.razor
> fix:Enter the secondary menu, mini menu has no selection effect

- src/Masa.Stack.Components/Shared/IntegrationComponents/SSheetDialog.razor
https://github.com/masastack/MASA.TSC/issues/406
> feat: add loading for sheet dialog

- src/Masa.Stack.Components/Shared/IntegrationComponents/DateTime/SDateTimeRangeToolbar.razor
- tests/MasaWebApp/Pages/DateTimeRangePickerExample.razor
the same bug in :  https://github.com/masastack/MASA.TSC/issues/433
> fix: the datetime ranger can not change value

- src/Masa.Stack.Components/Shared/Layouts/Components/User.razor
> fix:icon+ text buttons, ICONS don't need tooltips

- src/Masa.Stack.Components/Locales/zh-CN.json
- src/Masa.Stack.Components/Shared/IntegrationComponents/SIcon.razor.cs
_I18n Remove changed to Delete_
> Fix: I18n Remove changed to Delete

- src/Masa.Stack.Components/Shared/Layouts/Components/User.razor
> 🐛 fix(UserTeams): The selection may be highlighted incorrectly

- src/Masa.Stack.Components/wwwroot/css/app.css
_style: Align the STextField help icon with the STextField button icon_
> style: Align the STextField help icon with the STextField button icon

- src/Masa.Stack.Components/Shared/Layouts/Components/Breadcrumbs.razor.cs
fixes masastack/MASA.Auth#1158
> 🐛 fix(Breadcrumbs): update match rules

- src/Masa.Stack.Components/Masa.Stack.Components.csproj
- src/Masa.Stack.Components/Shared/IntegrationComponents/DateTime/SDateTimeRangePicker.razor
- src/Masa.Stack.Components/Shared/IntegrationComponents/DateTime/STimeSelector.razor
- src/Masa.Stack.Components/Shared/Layouts/Components/Breadcrumbs.razor.cs
- breadcumb url parameter decoded     
- datetimepicker add class d-flex
> fix: fix breadcumb

- src/Masa.Stack.Components/wwwroot/css/app.css
> 💄 style(Navigation): adjust the margin between list group and adjacent list item

- src/Masa.Stack.Components/RenderFragments.cs
- src/Masa.Stack.Components/Shared/IntegrationComponents/Users/SUserAutoComplete.razor
- src/Masa.Stack.Components/wwwroot/css/app.css
```razor
<MAutocomplete>
<ItemContent Context="data">
@RenderFragments.UserSelectItem(data.Item.Avatar, data.Item.DisplayName, data.Item.PhoneNumber, data.Item.Account, data.Item.Email)
</ItemContent>
</MAutocomplete>
```
related issue: #477
> 🆕 feat: add user-select-item template

- src/Masa.Stack.Components.Standalone/Masa.Stack.Components.Standalone.csproj
- src/Masa.Stack.Components/Extensions/OpenIdConnect/TokenEndpoint.cs
> chore: update Masa.Blazor version and remove TokenEndpoint
